CODE_FONT = ("Andale Mono", 10)
BOLD_FONT = 'default 12 bold'

GREY_TEXT = 'grey'
PY_FILE = 'py'
PY_METHOD_DEF = 'def '
SELF_PARAM_VALUE = 'self'

MAX_FILE_LENGTH = 2**20
MAX_LINES_OF_CODE = 15
MAX_PARAMETER_COUNT = 3
MAX_JACCARD_SIMILARITY = 0.25

PROMPT_FILE='refactor-prompt.txt'